version: '3.9'

networks:
  newrx:
    driver: "bridge"
    

# volumes:
  #  db-data:

services:

#PHP-FPM service
  app:
    build: .
    container_name: newrx
    restart: unless-stopped
    tty: true
    working_dir: /var/www/newrx
    depends_on:
      - db

    volumes:
      - ./:/var/www/newrx
      - ./docker-files/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    networks:
      - newrx

#   #NGINX service
  newrx_webserver: 
    image: nginx
    container_name: newrx_webserver
    restart: unless-stopped
    # tty: true
    
    ports:
      - '3000:80'
      - '3001:443'
    
    volumes:
      - ./:/var/www/newrx
      - ./docker-files/nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf
    
    networks:
      - newrx
      
  db:
    platform: linux/x86_64
    container_name: newrx_db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    # tty: true
    ports:
      -  "3307:3306"

    volumes:
      # - db-data:/var/lib/mysql
      # - ./docker-files/mysql/mysql.cnf:/etc/mysql/mysql.cnf

      -  ./storage/dbdata:/var/lib/mysql
      -  ./docker-files/mysql/mysql.cnf:/etc/mysql/mysql.cnf

    networks:
      - newrx

# Adminer service
  adminer:
    container_name: newrx_adminer
    image: adminer:latest
    restart: always
    ports:
      - "3002:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - newrx